import type { Metadata } from "next";
import { Bricolage_Grotesque, Mona_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const bricolage = Bricolage_Grotesque({
  subsets:["latin"],
  weight:["300", "400", "500", "600", "700"],
  variable: "--font-bricolage",
  display: "swap"
})
const monaSans = Mona_Sans({
  subsets:["latin"],
  weight:["300", "400", "500", "600", "700"],
  variable: "--font-mona",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.variable} ${monaSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
